[package]
name = "check-jitter"
version = "0.1.0"
edition = "2021"
authors = ["Johan Thorén <johan@thoren.xyz>"]
description = "A Nagios compatible plugin to measure network jitter."
readme = "README.md"
license = "ISC"
repository = "https://github.com/johanthoren/check_jitter"

[lib]
path = "src/lib.rs"

[[bin]]
name = "check_jitter"
path = "src/main.rs"

[dependencies]
ping = "0.5.2"
url = "2.5.0"
thiserror = "1.0.56"
log = "0.4.18"
clap = { version = "4.2.7", features = ["derive"] }
stderrlog = "0.5.4"
nagios-range = "0.2.5"
plist = "1.4.3"
psutil = "3.2.2"
serde = { version = "1.0.162", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "1.3.0"
assert_cmd = "2.0.11"
predicates = "3.0.3"
tempfile = "3.6.0"
