#!/bin/sh
# Post-installation script for setting capabilities

if command -v setcap >/dev/null 2>&1; then
    setcap cap_net_raw+ep /usr/bin/check_jitter || echo "Warning: setcap failed. Make sure /usr/bin/check_jitter has the necessary capabilities."
else
    echo "Warning: setcap not found. Make sure /usr/bin/check_jitter has the necessary capabilities."
fi

exit 0
